### PR TITLE
Feature/v032

### PR DESCRIPTION
**Pull request by greermichael**
## Changed
- Updated `terraform-aws-operations-account` module to v0.3.1
- Updated `terraform-aws-application-account` module to v0.3.1
## Added
- Inputs to enable autoscaling features of deployed cluster
- Input to enable helm installation
- Input for cluster tagging on cluster (Application environment)

### CODE REVIEW

**Comment by MarcoInnovations** [comment]
Why are we still referring to 'eu-central-1' as it is clearly an example set of code.  I would like to propose to call it 'example' alike other github projects are treating this.

**Comment by greermichael** [comment]
Go for it and make a PR

**Comment by radepal** [comment]
eu-central-1 at least presentat real aws region name

**Comment by radepal** [comment]
Will conflict with https://github.com/kentrikos/template-environment-configuration/pull/20
By rename of all paths

**Comment by MarcoInnovations** [comment]
But in this folder there is nothing but placeholders.  You fill out your variables (preferably by a script) and then put those real values in an aws region name.

Best Regards,

Marco Smit
cloud-sculptor
Group IT - FG-AM-6
Desk:        +1 864 802 6075
Mail:         marco.smit@bmwgroup.com<mailto:marco.smit@bmwgroup.com>

**Pull request merged**
